### ISSUE TITLE
Why did you choose CLIP for searching the closest in-context pair?

### ISSUE THREAD

**Issue by hdnminh** [Jackieam/InMeMo#4]
Hi Jiahao Zhang,

I have read your fascinating paper - InMeMo. I must admit that your contributions to this field are quite novel and significant.

**I have a question:** 
Why did you choose CLIP for searching the closest in-context pair? CLIP has been trained on multimodal (image & text) data. 
However, the input consists of images only in your setup. 
Why didn't you use a feature extractor trained specifically on images, such as SAM, etc.?

**Comment by Jackieam** [comment]
Hi! Thank you for your interest.
We followed the previous study that used CLIP as a feature extractor.
I recommend you to check that paper, they also used a different model for feature extraction and conducted experiments. Here is the paper:
"What Makes Good Examples for Visual In-Context Learning?"
